# 03 · Label train/test with an LLM, fine-tune RoBERTa (16-label system, v1)

**Step 8.** Label the 16,328-review train set and 4,083-review test set with GPT-4.1-mini
(3 runs + majority vote, with a GPT-4o-mini fallback).

**Step 9.** Fine-tune RoBERTa for multi-label classification over **20 classes**
(16 emotions + 4 evaluation dimensions) and compare four configurations:

| config | change |
|---|---|
| `config1_baseline` | roberta-large, 2e-5 |
| `config2_higher_lr` | 5e-5 |
| `config3_roberta_base` | smaller model |
| `config4_long_context` | 256 tokens |

Everything is scored on the human-labeled holdout. A threshold sweep on config 1 follows.

**Takeaway:** best macro F1 was **0.600**. Rare emotions such as Sadness and Guilt scored 0.00 and dragged the
macro average down, which motivated the redesign in notebook 04.

**Needs:** a GPU, `OPENAI_API_KEY`, the files from notebooks 01 to 02, and the human-labeled holdout.

In [ ]:
# ── Setup (runs locally or on Colab) ─────────────────────────────────────────
# Install dependencies first:  pip install -r requirements.txt
import os

# Where datasets, LLM labels, checkpoints and models are written (not committed to git).
# Colab: mount Drive and set CAPSTONE_DATA_DIR to a Drive folder to persist between sessions.
DATA_DIR = os.environ.get("CAPSTONE_DATA_DIR", "data")
os.makedirs(DATA_DIR, exist_ok=True)
OUTPUT_DIR = DATA_DIR

# API keys: environment variables first, Colab Secrets as a fallback.
_ENV_NAMES = {
    "claude": "ANTHROPIC_API_KEY",
    "gemini": "GEMINI_API_KEY",
    "xai": "XAI_API_KEY",
    "deepseek": "DEEPSEEK_API_KEY",
    "minimax": "MINIMAX_API_KEY",
}

def get_api_key(name):
    value = os.environ.get(_ENV_NAMES.get(name, name)) or os.environ.get(name)
    if value:
        return value
    try:
        from google.colab import userdata as _colab_userdata
        return _colab_userdata.get(name)
    except Exception:
        return None

class userdata:  # drop-in for google.colab.userdata
    get = staticmethod(get_api_key)

In [ ]:
# Imports used by the labeling cells below
import json, time, datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
import numpy as np
import pandas as pd
from tqdm import tqdm
from openai import OpenAI

In [ ]:
# ── CELL 1: Step 8 config ─────────────────────────────────────────────────────
TRAIN_DIR      = f"{OUTPUT_DIR}/train_llm_labels"
CHECKPOINT_DIR = f"{OUTPUT_DIR}/checkpoints_train"
os.makedirs(TRAIN_DIR,      exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

PRIMARY_VENDOR  = "openai"
PRIMARY_MODEL   = "gpt-4.1-mini"
FALLBACK_VENDOR = "openai"
FALLBACK_MODEL  = "gpt-4o-mini"
RUNS            = [1, 2, 3]

SYSTEM_PROMPT = """Label this product review for a consumer psychology study.

TASK A — EMOTIONS (multi-label, binary 0/1):
Return 1 if clearly present, 0 if not. Only label with explicit evidence.
Joy, Love, Surprise, Pride, Gratitude, Contentment, Relief, Hope, Interest,
Anger, Frustration, Disappointment, Sadness, Fear, Guilt, Disgust

TASK B — EVALUATIONS (single label each):
Trust: Low / Medium / High
Commitment: Low / Medium / High
Recommendation: Would Not Recommend / Neutral / Would Recommend
Sentiment: Negative / Neutral / Positive

Rules: explicit evidence only, middle label if unclear, no skipping eval dims.

Return ONLY this JSON, nothing else:
{
  "emotions": {
    "Joy": 0, "Love": 0, "Surprise": 0, "Pride": 0, "Gratitude": 0,
    "Contentment": 0, "Relief": 0, "Hope": 0, "Interest": 0,
    "Anger": 0, "Frustration": 0, "Disappointment": 0,
    "Sadness": 0, "Fear": 0, "Guilt": 0, "Disgust": 0
  },
  "Trust": "Medium",
  "Commitment": "Medium",
  "Recommendation": "Neutral",
  "Sentiment": "Neutral"
}"""

print("✓ Step 8 config loaded")
print(f"  Primary  : {PRIMARY_VENDOR}/{PRIMARY_MODEL}")
print(f"  Fallback : {FALLBACK_VENDOR}/{FALLBACK_MODEL}")

✓ Step 8 config loaded
  Primary  : openai/gpt-4.1-mini
  Fallback : openai/gpt-4o-mini

In [ ]:
# ── CELL 2: Parse + cost ──────────────────────────────────────────────────────
def parse_response_full(text, used_vendor, used_model):
    try:
        text = text.strip()
        if "</think>" in text:
            text = text.split("</think>")[-1].strip()
        if "```" in text:
            lines = [l for l in text.split("\n") if not l.strip().startswith("```")]
            text  = "\n".join(lines).strip()

        start = text.find("{")
        if start == -1:
            return None, None, "No JSON found"

        depth, end = 0, start
        for i, ch in enumerate(text[start:], start):
            if ch == "{":   depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break
        if depth > 0:
            text = text + "}" * depth

        data = json.loads(text[start:end] if depth == 0 else text[start:])

        emotions_out = {}
        raw_em = data.get("emotions", {})
        for em in EMOTIONS:
            emotions_out[em] = int(bool(raw_em.get(em, 0)))

        eval_out = {}
        for dim, levels in EVAL_DIMS.items():
            val = data.get(dim, "")
            eval_out[dim] = val if val in levels else levels[len(levels) // 2]

        return emotions_out, eval_out, None

    except Exception as e:
        return None, None, str(e)

def compute_cost_full(vendor, model, input_tokens, output_tokens):
    prices = {
        ("openai", "gpt-4.1-mini"): (0.40, 1.60),
        ("openai", "gpt-4o-mini"):  (0.15, 0.60),
    }
    price_in, price_out = prices.get((vendor, model), (0.40, 1.60))
    return (input_tokens / 1e6) * price_in + (output_tokens / 1e6) * price_out

print("✓ Parse + cost ready")

✓ Parse + cost ready

In [ ]:
# ── CELL 3: API call + classify ───────────────────────────────────────────────
def call_openai_full(review_text, model, system_prompt):
    client = OpenAI(api_key=get_api_key("OPENAI_API_KEY"))
    resp   = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": review_text[:2000]}
        ],
        temperature=0,
        max_tokens=300,
        response_format={"type": "json_object"},
    )
    return resp.choices[0].message.content or "", resp.usage.prompt_tokens, resp.usage.completion_tokens

def classify_review_full(row_id, review_text, retries=3):
    wait_times  = [3, 6, 15]
    used_vendor = PRIMARY_VENDOR
    used_model  = PRIMARY_MODEL

    for attempt in range(retries):
        try:
            t0 = time.perf_counter()
            raw, in_tok, out_tok = call_openai_full(review_text, used_model, SYSTEM_PROMPT)
            latency = time.perf_counter() - t0

            emotions_out, eval_out, err = parse_response_full(raw, used_vendor, used_model)
            if err:
                raise ValueError(err)

            cost   = compute_cost_full(used_vendor, used_model, in_tok, out_tok)
            record = {
                "id":          row_id,
                "review_text": review_text,
                "error":       None,
                "cost_usd":    cost,
                "latency_s":   latency,
                "model_used":  used_model,
            }
            for em in EMOTIONS:
                record[em] = emotions_out.get(em, 0)
            for dim in EVAL_DIMS:
                record[dim] = eval_out.get(dim, EVAL_DIMS[dim][len(EVAL_DIMS[dim]) // 2])
            return record

        except Exception as e:
            err_str       = str(e)
            is_rate_limit = any(x in err_str.lower() for x in ["rate", "429", "ratelimit"])

            if is_rate_limit and used_model == PRIMARY_MODEL:
                print(f"  ⚠ Rate limit row {row_id}, falling back to {FALLBACK_MODEL}")
                used_vendor = FALLBACK_VENDOR
                used_model  = FALLBACK_MODEL
                time.sleep(5)
                continue

            if attempt < retries - 1:
                time.sleep(60 if is_rate_limit else wait_times[attempt])
            else:
                record = {
                    "id":          row_id,
                    "review_text": review_text,
                    "error":       err_str,
                    "cost_usd":    0,
                    "latency_s":   0,
                    "model_used":  used_model,
                }
                for em in EMOTIONS:
                    record[em] = 0
                for dim in EVAL_DIMS:
                    record[dim] = EVAL_DIMS[dim][len(EVAL_DIMS[dim]) // 2]
                return record

print("✓ classify_review_full() ready")

✓ classify_review_full() ready

In [ ]:
# ── CELL 4: run_dataset — one dataset, one run ────────────────────────────────
def run_dataset(dataset_name, csv_path, run=1, max_workers=20):
    base_name = f"{dataset_name}_gpt41mini_run{run}"
    ckpt_path = f"{CHECKPOINT_DIR}/{base_name}.pkl"
    run_dir   = f"{TRAIN_DIR}/Run{run}"
    out_path  = f"{run_dir}/{base_name}.pkl"
    os.makedirs(run_dir, exist_ok=True)

    df       = pd.read_csv(csv_path)
    df["id"] = df.index

    results, processed_ids = [], set()
    if os.path.exists(ckpt_path):
        try:
            ck            = pd.read_pickle(ckpt_path)
            ok            = ck[ck["error"].isna()]
            results       = ok.to_dict("records")
            processed_ids = set(ok["id"].values)
            print(f"  Resuming {dataset_name} run{run}: {len(results)} done, {len(df)-len(results)} remaining")
        except Exception as e:
            print(f"  Could not load checkpoint: {e}")
    else:
        print(f"  Starting fresh: {dataset_name} run{run} — {len(df)} reviews")

    df_todo = df[~df["id"].isin(processed_ids)].copy()
    lock    = __import__("threading").Lock()
    start   = datetime.datetime.now()

    rows = [row for _, row in df_todo.iterrows()]

    print(f"\n{'='*60}")
    print(f"  {dataset_name} | run {run} | workers: {max_workers}")
    print(f"  Model: {PRIMARY_MODEL} (fallback: {FALLBACK_MODEL})")
    print(f"  Reviews: {len(df)} total | {len(df_todo)} remaining")
    print(f"{'='*60}")

    completed = 0
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(classify_review_full, row["id"], row["review_text"]): row["id"] for row in rows}
        for future in tqdm(as_completed(futures), total=len(futures), desc=f"{dataset_name} run{run}"):
            res = future.result()
            with lock:
                results.append(res)
                completed += 1
                if completed % 200 == 0:
                    pd.DataFrame(results).to_pickle(ckpt_path)
                    cost_so_far = sum(r["cost_usd"] for r in results if not r["error"])
                    elapsed     = (datetime.datetime.now() - start).total_seconds()
                    print(f"\n  [{completed}/{len(df_todo)}] checkpoint | cost: ${cost_so_far:.4f} | {elapsed/60:.1f}m elapsed")

    df_out = pd.DataFrame(results)
    df_out.to_pickle(ckpt_path)
    df_out.to_pickle(out_path)
    df_out.to_csv(out_path.replace(".pkl", ".csv"), index=False)

    ok         = df_out[df_out["error"].isna()]
    total_cost = ok["cost_usd"].sum()
    duration   = (datetime.datetime.now() - start).total_seconds()
    print(f"\n✓ {dataset_name} run {run} complete")
    print(f"  Successful : {len(ok)}/{len(df_out)}")
    print(f"  Cost       : ${total_cost:.4f}")
    print(f"  Runtime    : {duration:.0f}s ({duration/60:.1f}m)")
    return df_out

print("✓ run_dataset() ready")

✓ run_dataset() ready

In [ ]:
# ── CELL 5: majority vote ─────────────────────────────────────────────────────
def compute_majority_vote_final(dataset_name, runs=RUNS):
    run_dfs = {}
    for run in runs:
        path = f"{TRAIN_DIR}/Run{run}/{dataset_name}_gpt41mini_run{run}.pkl"
        if not os.path.exists(path):
            print(f"✗ Missing run {run}")
            return None
        df           = pd.read_pickle(path)
        run_dfs[run] = df[df["error"].isna()].set_index("id")

    common_ids = sorted(set.intersection(*[set(run_dfs[r].index) for r in runs]))
    print(f"Common reviews across {len(runs)} runs: {len(common_ids)}")

    results = []
    for row_id in tqdm(common_ids, desc=f"{dataset_name} majority vote"):
        rows   = {run: run_dfs[run].loc[row_id] for run in runs}
        record = {
            "id":          row_id,
            "review_text": rows[runs[0]]["review_text"],
        }
        for em in EMOTIONS:
            votes          = sum(int(rows[run].get(em, 0) or 0) for run in runs)
            record[em]     = 1 if votes > len(runs) / 2 else 0
            record[f"{em}_votes"] = votes
        for dim, levels in EVAL_DIMS.items():
            level_votes = {lv: 0 for lv in levels}
            for run in runs:
                val = rows[run].get(dim)
                if val in level_votes:
                    level_votes[val] += 1
            record[dim]            = max(level_votes, key=level_votes.get)
            record[f"{dim}_votes"] = level_votes
        results.append(record)

    df_mv = pd.DataFrame(results)
    out   = f"{TRAIN_DIR}/{dataset_name}_final_labeled.pkl"
    df_mv.to_pickle(out)
    df_mv.to_csv(out.replace(".pkl", ".csv"), index=False)

    print(f"\n✓ {dataset_name} majority vote complete: {len(df_mv)} reviews")
    print(f"\nLabel distribution:")
    for em in EMOTIONS:
        count = df_mv[em].sum()
        print(f"  {em:<15}: {count} ({count/len(df_mv)*100:.1f}%)")
    for dim in EVAL_DIMS:
        print(f"  {dim:<15}: {df_mv[dim].value_counts().to_dict()}")
    return df_mv

print("✓ compute_majority_vote_final() ready")

✓ compute_majority_vote_final() ready

In [ ]:
# ── CELL 6: EXECUTE ───────────────────────────────────────────────────────────
TRAIN_CSV = f"{OUTPUT_DIR}/train_final_v3.csv"
TEST_CSV  = f"{OUTPUT_DIR}/test_final_v3.csv"

# ── Train: all 3 runs then majority vote ──────────────────────────────────────
for run in RUNS:
    run_dataset("train", TRAIN_CSV, run=run, max_workers=20)

df_train_labeled = compute_majority_vote_final("train", runs=RUNS)

# ── Test: all 3 runs then majority vote ───────────────────────────────────────
for run in RUNS:
    run_dataset("test", TEST_CSV, run=run, max_workers=20)

df_test_labeled = compute_majority_vote_final("test", runs=RUNS)

print("\n✓ Step 8 complete")
print(f"  Train: {len(df_train_labeled)} labeled reviews → {TRAIN_DIR}/train_final_labeled.csv")
print(f"  Test : {len(df_test_labeled)} labeled reviews → {TRAIN_DIR}/test_final_labeled.csv")

  Resuming train run1: 16328 done, 0 remaining

============================================================
  train | run 1 | workers: 20
  Model: gpt-4.1-mini (fallback: gpt-4o-mini)
  Reviews: 16328 total | 0 remaining
============================================================

train run1: 0it [00:00, ?it/s]

✓ train run 1 complete
  Successful : 16328/16328
  Cost       : $6.7799
  Runtime    : 2s (0.0m)
  Resuming train run2: 16328 done, 0 remaining

============================================================
  train | run 2 | workers: 20
  Model: gpt-4.1-mini (fallback: gpt-4o-mini)
  Reviews: 16328 total | 0 remaining
============================================================

train run2: 0it [00:00, ?it/s]

✓ train run 2 complete
  Successful : 16328/16328
  Cost       : $6.7832
  Runtime    : 4s (0.1m)
  Resuming train run3: 10800 done, 5528 remaining

============================================================
  train | run 3 | workers: 20
  Model: gpt-4.1-mini (fallback: gpt-4o-mini)
  Reviews: 16328 total | 5528 remaining
============================================================

train run3:   4%|▎         | 202/5528 [00:43<21:30,  4.13it/s]

  [200/5528] checkpoint | cost: $4.5716 | 0.7m elapsed

train run3:   7%|▋         | 404/5528 [01:17<06:41, 12.78it/s]

  [400/5528] checkpoint | cost: $4.6538 | 1.3m elapsed

train run3:  11%|█         | 600/5528 [01:53<15:56,  5.15it/s]

  [600/5528] checkpoint | cost: $4.7364 | 1.9m elapsed

train run3:  15%|█▍        | 802/5528 [02:29<12:00,  6.56it/s]

  [800/5528] checkpoint | cost: $4.8196 | 2.5m elapsed

train run3:  18%|█▊        | 1000/5528 [03:05<16:45,  4.50it/s]

  [1000/5528] checkpoint | cost: $4.9025 | 3.1m elapsed

train run3:  22%|██▏       | 1206/5528 [03:40<08:07,  8.86it/s]

  [1200/5528] checkpoint | cost: $4.9854 | 3.7m elapsed

train run3:  25%|██▌       | 1400/5528 [04:16<13:12,  5.21it/s]

  [1400/5528] checkpoint | cost: $5.0689 | 4.3m elapsed

train run3:  29%|██▉       | 1600/5528 [04:52<11:15,  5.81it/s]

  [1600/5528] checkpoint | cost: $5.1511 | 4.9m elapsed

train run3:  33%|███▎      | 1803/5528 [05:28<11:54,  5.21it/s]

  [1800/5528] checkpoint | cost: $5.2341 | 5.5m elapsed

train run3:  36%|███▌      | 2003/5528 [06:04<11:58,  4.91it/s]

  [2000/5528] checkpoint | cost: $5.3177 | 6.1m elapsed

train run3:  40%|███▉      | 2204/5528 [06:40<07:42,  7.19it/s]

  [2200/5528] checkpoint | cost: $5.4015 | 6.7m elapsed

train run3:  43%|████▎     | 2400/5528 [07:16<16:08,  3.23it/s]

  [2400/5528] checkpoint | cost: $5.4845 | 7.3m elapsed

train run3:  47%|████▋     | 2600/5528 [07:51<09:20,  5.22it/s]

  [2600/5528] checkpoint | cost: $5.5675 | 7.9m elapsed

train run3:  51%|█████     | 2803/5528 [08:28<05:55,  7.68it/s]

  [2800/5528] checkpoint | cost: $5.6508 | 8.5m elapsed

train run3:  54%|█████▍    | 3000/5528 [09:05<12:30,  3.37it/s]

  [3000/5528] checkpoint | cost: $5.7339 | 9.1m elapsed

train run3:  58%|█████▊    | 3200/5528 [09:42<11:48,  3.29it/s]

  [3200/5528] checkpoint | cost: $5.8165 | 9.7m elapsed

train run3:  62%|██████▏   | 3401/5528 [10:18<06:31,  5.43it/s]

  [3400/5528] checkpoint | cost: $5.8990 | 10.3m elapsed

train run3:  65%|██████▌   | 3600/5528 [10:54<06:32,  4.91it/s]

  [3600/5528] checkpoint | cost: $5.9822 | 10.9m elapsed

train run3:  69%|██████▊   | 3800/5528 [11:31<05:46,  4.98it/s]

  [3800/5528] checkpoint | cost: $6.0641 | 11.5m elapsed

train run3:  72%|███████▏  | 4000/5528 [12:07<06:37,  3.84it/s]

  [4000/5528] checkpoint | cost: $6.1474 | 12.1m elapsed

train run3:  76%|███████▌  | 4200/5528 [12:43<06:19,  3.49it/s]

  [4200/5528] checkpoint | cost: $6.2310 | 12.7m elapsed

train run3:  80%|███████▉  | 4403/5528 [13:20<03:10,  5.90it/s]

  [4400/5528] checkpoint | cost: $6.3138 | 13.3m elapsed

train run3:  83%|████████▎ | 4600/5528 [13:58<02:12,  7.00it/s]

  [4600/5528] checkpoint | cost: $6.3960 | 14.0m elapsed

train run3:  87%|████████▋ | 4800/5528 [14:37<03:15,  3.72it/s]

  [4800/5528] checkpoint | cost: $6.4782 | 14.6m elapsed

train run3:  91%|█████████ | 5003/5528 [15:16<01:15,  6.92it/s]

  [5000/5528] checkpoint | cost: $6.5621 | 15.3m elapsed

train run3:  94%|█████████▍| 5200/5528 [15:53<01:54,  2.86it/s]

  [5200/5528] checkpoint | cost: $6.6447 | 15.9m elapsed

train run3:  98%|█████████▊| 5400/5528 [16:30<00:33,  3.83it/s]

  [5400/5528] checkpoint | cost: $6.7280 | 16.5m elapsed

train run3: 100%|██████████| 5528/5528 [17:13<00:00,  5.35it/s]

✓ train run 3 complete
  Successful : 16328/16328
  Cost       : $6.7813
  Runtime    : 1035s (17.3m)
Common reviews across 3 runs: 16328

train majority vote: 100%|██████████| 16328/16328 [00:08<00:00, 1830.23it/s]

✓ train majority vote complete: 16328 reviews

Label distribution:
  Joy            : 7758 (47.5%)
  Love           : 2970 (18.2%)
  Surprise       : 947 (5.8%)
  Pride          : 255 (1.6%)
  Gratitude      : 770 (4.7%)
  Contentment    : 8471 (51.9%)
  Relief         : 2065 (12.6%)
  Hope           : 1790 (11.0%)
  Interest       : 2195 (13.4%)
  Anger          : 916 (5.6%)
  Frustration    : 5155 (31.6%)
  Disappointment : 6556 (40.2%)
  Sadness        : 87 (0.5%)
  Fear           : 268 (1.6%)
  Guilt          : 46 (0.3%)
  Disgust        : 749 (4.6%)
  Trust          : {'High': 7058, 'Medium': 6245, 'Low': 3025}
  Commitment     : {'Medium': 7832, 'High': 4624, 'Low': 3872}
  Recommendation : {'Would Recommend': 6574, 'Neutral': 6277, 'Would Not Recommend': 3477}
  Sentiment      : {'Positive': 7943, 'Neutral': 4649, 'Negative': 3736}
  Starting fresh: test run1 — 4083 reviews

============================================================
  test | run 1 | workers: 20
  Model: gpt-4.1-mini (fallback: gpt-4o-mini)
  Reviews: 4083 total | 4083 remaining
============================================================

test run1:   5%|▍         | 200/4083 [00:40<16:33,  3.91it/s]

  [200/4083] checkpoint | cost: $0.0829 | 0.7m elapsed

test run1:  10%|▉         | 400/4083 [01:15<11:16,  5.45it/s]

  [400/4083] checkpoint | cost: $0.1662 | 1.3m elapsed

test run1:  15%|█▍        | 600/4083 [01:49<08:58,  6.47it/s]

  [600/4083] checkpoint | cost: $0.2495 | 1.9m elapsed

test run1:  20%|█▉        | 801/4083 [02:24<07:59,  6.85it/s]

  [800/4083] checkpoint | cost: $0.3310 | 2.4m elapsed

test run1:  25%|██▍       | 1001/4083 [02:59<07:59,  6.42it/s]

  [1000/4083] checkpoint | cost: $0.4136 | 3.0m elapsed

test run1:  29%|██▉       | 1200/4083 [03:33<07:26,  6.46it/s]

  [1200/4083] checkpoint | cost: $0.4975 | 3.6m elapsed

test run1:  34%|███▍      | 1401/4083 [04:08<06:54,  6.48it/s]

  [1400/4083] checkpoint | cost: $0.5804 | 4.2m elapsed

test run1:  39%|███▉      | 1600/4083 [04:42<05:48,  7.13it/s]

  [1600/4083] checkpoint | cost: $0.6649 | 4.7m elapsed

test run1:  44%|████▍     | 1800/4083 [05:17<05:23,  7.06it/s]

  [1800/4083] checkpoint | cost: $0.7478 | 5.3m elapsed

test run1:  49%|████▉     | 2001/4083 [05:52<06:25,  5.41it/s]

  [2000/4083] checkpoint | cost: $0.8307 | 5.9m elapsed

test run1:  54%|█████▍    | 2199/4083 [06:25<03:50,  8.18it/s]

  [2200/4083] checkpoint | cost: $0.9143 | 6.5m elapsed

test run1:  59%|█████▉    | 2401/4083 [07:00<04:03,  6.90it/s]

  [2400/4083] checkpoint | cost: $0.9971 | 7.0m elapsed

test run1:  64%|██████▎   | 2601/4083 [07:35<04:18,  5.73it/s]

  [2600/4083] checkpoint | cost: $1.0799 | 7.6m elapsed

test run1:  69%|██████▊   | 2800/4083 [08:08<03:05,  6.91it/s]

  [2800/4083] checkpoint | cost: $1.1628 | 8.2m elapsed

test run1:  73%|███████▎  | 2999/4083 [08:43<03:42,  4.87it/s]

  [3000/4083] checkpoint | cost: $1.2455 | 8.8m elapsed

test run1:  78%|███████▊  | 3200/4083 [09:19<03:05,  4.77it/s]

  [3200/4083] checkpoint | cost: $1.3283 | 9.3m elapsed

test run1:  83%|████████▎ | 3403/4083 [09:54<01:30,  7.51it/s]

  [3400/4083] checkpoint | cost: $1.4112 | 9.9m elapsed

test run1:  88%|████████▊ | 3600/4083 [10:29<02:11,  3.68it/s]

  [3600/4083] checkpoint | cost: $1.4938 | 10.5m elapsed

test run1:  93%|█████████▎| 3800/4083 [11:04<00:31,  8.87it/s]

  [3800/4083] checkpoint | cost: $1.5764 | 11.1m elapsed

test run1:  98%|█████████▊| 4003/4083 [11:41<00:10,  7.74it/s]

  [4000/4083] checkpoint | cost: $1.6593 | 11.7m elapsed

test run1: 100%|██████████| 4083/4083 [12:00<00:00,  5.67it/s]

✓ test run 1 complete
  Successful : 4083/4083
  Cost       : $1.6935
  Runtime    : 722s (12.0m)
  Starting fresh: test run2 — 4083 reviews

============================================================
  test | run 2 | workers: 20
  Model: gpt-4.1-mini (fallback: gpt-4o-mini)
  Reviews: 4083 total | 4083 remaining
============================================================

test run2:   5%|▍         | 201/4083 [00:40<09:14,  7.00it/s]

  [200/4083] checkpoint | cost: $0.0829 | 0.7m elapsed

test run2:  10%|▉         | 400/4083 [01:18<11:19,  5.42it/s]

  [400/4083] checkpoint | cost: $0.1661 | 1.3m elapsed

test run2:  15%|█▍        | 601/4083 [01:55<11:22,  5.10it/s]

  [600/4083] checkpoint | cost: $0.2495 | 1.9m elapsed

test run2:  20%|█▉        | 801/4083 [02:29<07:38,  7.16it/s]

  [800/4083] checkpoint | cost: $0.3310 | 2.5m elapsed

test run2:  24%|██▍       | 1000/4083 [03:09<13:17,  3.87it/s]

  [1000/4083] checkpoint | cost: $0.4138 | 3.2m elapsed

test run2:  29%|██▉       | 1200/4083 [03:54<07:18,  6.58it/s]

  [1200/4083] checkpoint | cost: $0.4975 | 3.9m elapsed

test run2:  34%|███▍      | 1400/4083 [04:40<10:13,  4.38it/s]

  [1400/4083] checkpoint | cost: $0.5805 | 4.7m elapsed

test run2:  39%|███▉      | 1602/4083 [05:23<05:57,  6.94it/s]

  [1600/4083] checkpoint | cost: $0.6650 | 5.4m elapsed

test run2:  44%|████▍     | 1801/4083 [06:08<07:54,  4.81it/s]

  [1800/4083] checkpoint | cost: $0.7480 | 6.1m elapsed

test run2:  49%|████▉     | 2002/4083 [06:52<07:28,  4.64it/s]

  [2000/4083] checkpoint | cost: $0.8310 | 6.9m elapsed

test run2:  54%|█████▍    | 2201/4083 [07:36<06:02,  5.20it/s]

  [2200/4083] checkpoint | cost: $0.9146 | 7.6m elapsed

test run2:  59%|█████▉    | 2399/4083 [08:18<02:58,  9.43it/s]

  [2400/4083] checkpoint | cost: $0.9974 | 8.3m elapsed

test run2:  64%|██████▎   | 2602/4083 [08:58<05:32,  4.45it/s]

  [2600/4083] checkpoint | cost: $1.0802 | 9.0m elapsed

test run2:  69%|██████▊   | 2800/4083 [09:35<04:23,  4.87it/s]

  [2800/4083] checkpoint | cost: $1.1631 | 9.6m elapsed

test run2:  73%|███████▎  | 3001/4083 [10:14<03:32,  5.09it/s]

  [3000/4083] checkpoint | cost: $1.2459 | 10.2m elapsed

test run2:  78%|███████▊  | 3199/4083 [11:09<04:53,  3.01it/s]

  [3200/4083] checkpoint | cost: $1.3287 | 11.2m elapsed

test run2:  83%|████████▎ | 3400/4083 [12:10<04:11,  2.71it/s]

  [3400/4083] checkpoint | cost: $1.4117 | 12.2m elapsed

test run2:  88%|████████▊ | 3604/4083 [12:53<01:01,  7.83it/s]

  [3600/4083] checkpoint | cost: $1.4944 | 12.9m elapsed

test run2:  93%|█████████▎| 3804/4083 [13:29<00:34,  8.16it/s]

  [3800/4083] checkpoint | cost: $1.5768 | 13.5m elapsed

test run2:  98%|█████████▊| 4000/4083 [14:05<00:16,  4.99it/s]

  [4000/4083] checkpoint | cost: $1.6600 | 14.1m elapsed

test run2: 100%|██████████| 4083/4083 [14:21<00:00,  4.74it/s]

✓ test run 2 complete
  Successful : 4083/4083
  Cost       : $1.6942
  Runtime    : 862s (14.4m)
  Starting fresh: test run3 — 4083 reviews

============================================================
  test | run 3 | workers: 20
  Model: gpt-4.1-mini (fallback: gpt-4o-mini)
  Reviews: 4083 total | 4083 remaining
============================================================

test run3:   5%|▍         | 200/4083 [00:35<10:43,  6.03it/s]

  [200/4083] checkpoint | cost: $0.0828 | 0.6m elapsed

test run3:  10%|▉         | 401/4083 [01:11<11:40,  5.26it/s]

  [400/4083] checkpoint | cost: $0.1661 | 1.2m elapsed

test run3:  15%|█▍        | 600/4083 [01:46<10:47,  5.38it/s]

  [600/4083] checkpoint | cost: $0.2496 | 1.8m elapsed

test run3:  20%|█▉        | 801/4083 [02:20<07:05,  7.72it/s]

  [800/4083] checkpoint | cost: $0.3311 | 2.4m elapsed

test run3:  25%|██▍       | 1003/4083 [02:55<05:45,  8.91it/s]

  [1000/4083] checkpoint | cost: $0.4139 | 2.9m elapsed

test run3:  29%|██▉       | 1200/4083 [03:29<09:43,  4.94it/s]

  [1200/4083] checkpoint | cost: $0.4978 | 3.5m elapsed

test run3:  34%|███▍      | 1400/4083 [04:04<08:11,  5.46it/s]

  [1400/4083] checkpoint | cost: $0.5807 | 4.1m elapsed

test run3:  39%|███▉      | 1599/4083 [04:40<05:10,  8.01it/s]

  [1600/4083] checkpoint | cost: $0.6654 | 4.7m elapsed

test run3:  44%|████▍     | 1803/4083 [05:16<04:25,  8.58it/s]

  [1800/4083] checkpoint | cost: $0.7484 | 5.3m elapsed

test run3:  49%|████▉     | 2004/4083 [05:50<03:39,  9.45it/s]

  [2000/4083] checkpoint | cost: $0.8315 | 5.9m elapsed

test run3:  54%|█████▍    | 2200/4083 [06:23<04:04,  7.70it/s]

  [2200/4083] checkpoint | cost: $0.9151 | 6.4m elapsed

test run3:  59%|█████▉    | 2400/4083 [06:57<04:15,  6.58it/s]

  [2400/4083] checkpoint | cost: $0.9980 | 7.0m elapsed

test run3:  64%|██████▎   | 2602/4083 [07:31<03:50,  6.41it/s]

  [2600/4083] checkpoint | cost: $1.0808 | 7.5m elapsed

test run3:  69%|██████▊   | 2800/4083 [08:05<03:29,  6.13it/s]

  [2800/4083] checkpoint | cost: $1.1638 | 8.1m elapsed

test run3:  73%|███████▎  | 3000/4083 [08:39<03:45,  4.79it/s]

  [3000/4083] checkpoint | cost: $1.2465 | 8.7m elapsed

test run3:  78%|███████▊  | 3200/4083 [09:13<02:55,  5.03it/s]

  [3200/4083] checkpoint | cost: $1.3294 | 9.3m elapsed

test run3:  83%|████████▎ | 3402/4083 [09:47<01:26,  7.85it/s]

  [3400/4083] checkpoint | cost: $1.4126 | 9.8m elapsed

test run3:  88%|████████▊ | 3600/4083 [10:19<01:19,  6.04it/s]

  [3600/4083] checkpoint | cost: $1.4952 | 10.4m elapsed

test run3:  93%|█████████▎| 3800/4083 [10:54<00:35,  7.99it/s]

  [3800/4083] checkpoint | cost: $1.5778 | 10.9m elapsed

test run3:  98%|█████████▊| 4000/4083 [11:28<00:13,  6.34it/s]

  [4000/4083] checkpoint | cost: $1.6609 | 11.5m elapsed

test run3: 100%|██████████| 4083/4083 [11:43<00:00,  5.80it/s]

✓ test run 3 complete
  Successful : 4083/4083
  Cost       : $1.6950
  Runtime    : 705s (11.8m)
Common reviews across 3 runs: 4083

test majority vote: 100%|██████████| 4083/4083 [00:01<00:00, 3135.09it/s]

✓ test majority vote complete: 4083 reviews

Label distribution:
  Joy            : 2001 (49.0%)
  Love           : 734 (18.0%)
  Surprise       : 254 (6.2%)
  Pride          : 63 (1.5%)
  Gratitude      : 207 (5.1%)
  Contentment    : 2204 (54.0%)
  Relief         : 554 (13.6%)
  Hope           : 446 (10.9%)
  Interest       : 542 (13.3%)
  Anger          : 209 (5.1%)
  Frustration    : 1231 (30.1%)
  Disappointment : 1582 (38.7%)
  Sadness        : 25 (0.6%)
  Fear           : 61 (1.5%)
  Guilt          : 12 (0.3%)
  Disgust        : 171 (4.2%)
  Trust          : {'High': 1819, 'Medium': 1541, 'Low': 723}
  Commitment     : {'Medium': 1938, 'High': 1221, 'Low': 924}
  Recommendation : {'Would Recommend': 1707, 'Neutral': 1538, 'Would Not Recommend': 838}
  Sentiment      : {'Positive': 2024, 'Neutral': 1160, 'Negative': 899}

✓ Step 8 complete
  Train: 16328 labeled reviews → data/train_llm_labels/train_final_labeled.csv
  Test : 4083 labeled reviews → data/train_llm_labels/test_final_labeled.csv

In [ ]:
# ── CELL 1: Install + Imports ─────────────────────────────────────────────────

import os
import json
import torch
import numpy as np
import pandas as pd
from sklearn.metrics import (
    f1_score, roc_auc_score, matthews_corrcoef,
    precision_score, recall_score, hamming_loss,
    jaccard_score, confusion_matrix,
)
from transformers import (
    RobertaTokenizer,
    RobertaForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback,
)
from datasets import Dataset
import warnings
warnings.filterwarnings('ignore')

OUTPUT_DIR = DATA_DIR
TRAIN_DIR  = f"{OUTPUT_DIR}/train_llm_labels"

EMOTIONS = [
    "Joy", "Love", "Surprise", "Pride", "Gratitude",
    "Contentment", "Relief", "Hope", "Interest",
    "Anger", "Frustration", "Disappointment",
    "Sadness", "Fear", "Guilt", "Disgust"
]
EVAL_DIMS = ["Trust", "Commitment", "Recommendation", "Sentiment"]
CLASSES   = EMOTIONS + EVAL_DIMS
NUM_LABELS = len(CLASSES)

EVAL_BINARIZE = {
    "Trust":          {"High": 1, "Medium": 0, "Low": 0},
    "Commitment":     {"High": 1, "Medium": 0, "Low": 0},
    "Recommendation": {"Would Recommend": 1, "Neutral": 0, "Would Not Recommend": 0},
    "Sentiment":      {"Positive": 1, "Neutral": 0, "Negative": 0},
}

print("✓ Imports ready")
print(f"  Labels: {NUM_LABELS} ({len(EMOTIONS)} emotions + {len(EVAL_DIMS)} eval dims)")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 40.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 41.7 MB/s eta 0:00:00
✓ Imports ready
  Labels: 20 (16 emotions + 4 eval dims)

In [ ]:
# ── CELL 2: Load + Prepare Data (run once, reused across all configs) ──────────
print("="*60)
print("LOADING DATA")
print("="*60)

df_train_full = pd.read_csv(f"{TRAIN_DIR}/train_final_labeled.csv")
df_test       = pd.read_csv(f"{TRAIN_DIR}/test_final_labeled.csv")
df_holdout    = pd.read_csv(f"{OUTPUT_DIR}/final_holdout.csv")

# Clean holdout column names
emotion_rename = {
    "Joy (0/1)":             "Joy",
    "Love (0/1) ":           "Love",
    "Surprise (0/1)":        "Surprise",
    "Pride (0/1)":           "Pride",
    "Gratitude (0/1)":       "Gratitude",
    "Contentment (0/1)":     "Contentment",
    "Relief (0/1)":          "Relief",
    "Hope (0/1)":            "Hope",
    "Interest (0/1)":        "Interest",
    "Anger (0/1)":           "Anger",
    "Frustration (0/1)":     "Frustration",
    "Disappointment (0/1)":  "Disappointment",
    "Sadness (0/1)":         "Sadness",
    "Fear (0/1)":            "Fear",
    "Guilt (0/1)":           "Guilt",
    "Disgust (0/1)":         "Disgust",
}
eval_rename = {
    "Trust (Low / Medium / High)":                                             "Trust",
    "Commitment (Low / Medium / High)":                                        "Commitment",
    "Recommendation Intent (Would Not Recommend / Neutral / Would Recommend)": "Recommendation",
    "Sentiment (Negative / Neutral / Positive)":                               "Sentiment",
}
df_holdout = df_holdout.drop(columns=["Joy (0/1).1"], errors="ignore")
df_holdout = df_holdout.rename(columns={**emotion_rename, **eval_rename})

# Binarize eval dims across all splits
for dim, mapping in EVAL_BINARIZE.items():
    for df in [df_train_full, df_test, df_holdout]:
        if dim in df.columns:
            df[dim] = df[dim].map(mapping).fillna(0).astype(int)

print(f"Train full : {len(df_train_full)}")
print(f"Test       : {len(df_test)}")
print(f"Holdout    : {len(df_holdout)}")
print(f"Missing cols in holdout: {[c for c in CLASSES if c not in df_holdout.columns]}")

# Train/Val split — 90/10
try:
    from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
    msss = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=42)
    train_idx, val_idx = next(msss.split(df_train_full, df_train_full[EMOTIONS].values))
    df_train = df_train_full.iloc[train_idx].copy()
    df_val   = df_train_full.iloc[val_idx].copy()
    print("\nUsing: Iterative multi-label stratification")
except ImportError:
    from sklearn.model_selection import train_test_split
    df_train, df_val = train_test_split(df_train_full, test_size=0.1, random_state=42)
    print("\nUsing: Random split")

print(f"  Train      : {len(df_train)}")
print(f"  Validation : {len(df_val)}")

# Label arrays
train_labels   = df_train[CLASSES].values.astype(np.float32)
val_labels     = df_val[CLASSES].values.astype(np.float32)
test_labels    = df_test[CLASSES].values.astype(np.float32)
holdout_labels = df_holdout[CLASSES].values.astype(np.float32)

print(f"\nLabel distribution (train emotions):")
for i, cls in enumerate(EMOTIONS):
    count = train_labels[:, i].sum()
    print(f"  {cls:<15}: {int(count)} ({count/len(train_labels)*100:.1f}%)")

print("\n✓ Data ready")

============================================================
LOADING DATA
============================================================
Train full : 16328
Test       : 4083
Holdout    : 1441
Missing cols in holdout: []

Using: Iterative multi-label stratification
  Train      : 14695
  Validation : 1633

Label distribution (train emotions):
  Joy            : 6982 (47.5%)
  Love           : 2673 (18.2%)
  Surprise       : 852 (5.8%)
  Pride          : 229 (1.6%)
  Gratitude      : 693 (4.7%)
  Contentment    : 7624 (51.9%)
  Relief         : 1858 (12.6%)
  Hope           : 1611 (11.0%)
  Interest       : 1975 (13.4%)
  Anger          : 824 (5.6%)
  Frustration    : 4639 (31.6%)
  Disappointment : 5900 (40.1%)
  Sadness        : 78 (0.5%)
  Fear           : 241 (1.6%)
  Guilt          : 41 (0.3%)
  Disgust        : 674 (4.6%)

✓ Data ready

In [ ]:
# ── CELL 3: Evaluation functions (run once) ───────────────────────────────────
def evaluate_multilabel(y_true, y_pred, y_prob, class_names):
    per_class = {}
    for i, cls in enumerate(class_names):
        y_t, y_p, y_pr = y_true[:, i], y_pred[:, i], y_prob[:, i]
        try:
            auc = roc_auc_score(y_t, y_pr)
        except:
            auc = 0.0
        per_class[cls] = {
            'f1':        f1_score(y_t, y_p, zero_division=0),
            'precision': precision_score(y_t, y_p, zero_division=0),
            'recall':    recall_score(y_t, y_p, zero_division=0),
            'mcc':       matthews_corrcoef(y_t, y_p),
            'auc':       auc,
            'support':   int(y_t.sum()),
        }
    macro = {
        'f1_macro':        np.mean([per_class[c]['f1']        for c in class_names]),
        'precision_macro': np.mean([per_class[c]['precision'] for c in class_names]),
        'recall_macro':    np.mean([per_class[c]['recall']    for c in class_names]),
        'mcc_macro':       np.mean([per_class[c]['mcc']       for c in class_names]),
        'auc_macro':       np.mean([per_class[c]['auc']       for c in class_names]),
    }
    micro = {
        'f1_micro':        f1_score(y_true, y_pred, average='micro',   zero_division=0),
        'precision_micro': precision_score(y_true, y_pred, average='micro', zero_division=0),
        'recall_micro':    recall_score(y_true, y_pred, average='micro',    zero_division=0),
    }
    sample = {
        'f1_samples':      f1_score(y_true, y_pred, average='samples', zero_division=1),
        'jaccard_samples': jaccard_score(y_true, y_pred, average='samples', zero_division=1),
    }
    overall = {
        'exact_match_ratio': (y_pred == y_true).all(axis=1).mean(),
        'hamming_loss':      hamming_loss(y_true, y_pred),
    }
    return {'per_class': per_class, 'macro': macro, 'micro': micro,
            'sample': sample, 'overall': overall}

def print_report(metrics, class_names, config_name):
    print(f"\n{'='*70}")
    print(f"HOLDOUT EVALUATION — {config_name}")
    print(f"{'='*70}")
    print(f"\n{'Class':<16} {'F1':>7} {'AUC':>7} {'MCC':>7} {'Prec':>7} {'Rec':>7} {'Support':>8}")
    print("-"*62)
    for cls in class_names:
        m = metrics['per_class'][cls]
        print(f"{cls:<16} {m['f1']:>7.4f} {m['auc']:>7.4f} {m['mcc']:>7.4f} "
              f"{m['precision']:>7.4f} {m['recall']:>7.4f} {m['support']:>8}")
    print("-"*62)
    m = metrics['macro']
    print(f"{'Macro Avg':<16} {m['f1_macro']:>7.4f} {m['auc_macro']:>7.4f} "
          f"{m['mcc_macro']:>7.4f} {m['precision_macro']:>7.4f} {m['recall_macro']:>7.4f}")
    print(f"\n  Macro F1    : {metrics['macro']['f1_macro']:.4f}  ← Primary")
    print(f"  Macro AUC   : {metrics['macro']['auc_macro']:.4f}")
    print(f"  Macro MCC   : {metrics['macro']['mcc_macro']:.4f}")
    print(f"  Micro F1    : {metrics['micro']['f1_micro']:.4f}")
    print(f"  Exact Match : {metrics['overall']['exact_match_ratio']:.4f}")
    print(f"  Hamming Loss: {metrics['overall']['hamming_loss']:.4f}")

def save_results(metrics, trainer, config_name, model_name,
                 holdout_probs, holdout_preds, perf_path, hparams):
    df_preds = df_holdout.copy()
    for i, cls in enumerate(CLASSES):
        df_preds[f'{cls}_prob'] = holdout_probs[:, i]
        df_preds[f'{cls}_pred'] = holdout_preds[:, i]
    df_preds.to_csv(f"{perf_path}/holdout_predictions.csv", index=False)

    summary = {
        'config':          config_name,
        'model':           model_name,
        'macro':           metrics['macro'],
        'micro':           metrics['micro'],
        'sample':          metrics['sample'],
        'overall':         metrics['overall'],
        'per_class':       metrics['per_class'],
        'hyperparameters': hparams,
    }
    with open(f"{perf_path}/holdout_metrics.json", 'w') as f:
        json.dump(summary, f, indent=2, default=float)

    if trainer is not None:
        with open(f"{perf_path}/training_history.json", 'w') as f:
            json.dump(trainer.state.log_history, f, indent=2)

    print(f"✓ Saved to {perf_path}")

def get_device():
    if torch.cuda.is_available():
        device = torch.device("cuda")
        print(f"Device: CUDA ({torch.cuda.get_device_name(0)})")
        print(f"  VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
        return device, True, False
    else:
        print("Device: CPU")
        return torch.device("cpu"), False, False

print("✓ Evaluation functions ready")

✓ Evaluation functions ready

In [ ]:
# ── CELL 4: Tokenize (run once per MAX_LENGTH change) ─────────────────────────
MAX_LENGTH = 128  # start here — fast, covers median review length

tokenizer = RobertaTokenizer.from_pretrained("roberta-large")

def tokenize(texts, labels):
    enc = tokenizer(
        texts.tolist(),
        truncation=True,
        padding='max_length',
        max_length=MAX_LENGTH,
        return_tensors=None,
    )
    return Dataset.from_dict({
        'input_ids':      enc['input_ids'],
        'attention_mask': enc['attention_mask'],
        'labels':         labels.tolist(),
    })

print(f"Tokenizing at MAX_LENGTH={MAX_LENGTH}...")
train_dataset   = tokenize(df_train['review_text'].values,   train_labels)
val_dataset     = tokenize(df_val['review_text'].values,     val_labels)
test_dataset    = tokenize(df_test['review_text'].values,    test_labels)
holdout_dataset = tokenize(df_holdout['review_text'].values, holdout_labels)

lengths = [len(ids) for ids in train_dataset['input_ids']]
truncated = sum(1 for l in lengths if l == MAX_LENGTH)
print(f"  Train: {len(train_dataset)} | Val: {len(val_dataset)}")
print(f"  Truncated: {truncated}/{len(lengths)} ({truncated/len(lengths)*100:.1f}%)")
print("✓ Tokenization done")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Tokenizing at MAX_LENGTH=128...
  Train: 14695 | Val: 1633
  Truncated: 14695/14695 (100.0%)
✓ Tokenization done

In [ ]:
# ── CELL 5: Train + Evaluate one config ───────────────────────────────────────
def predict(dataset, model, device, batch_size=64):
    from torch.utils.data import DataLoader
    loader    = DataLoader(dataset, batch_size=batch_size)
    all_probs = []
    model.eval()
    with torch.no_grad():
        for batch in loader:
            input_ids      = torch.stack(batch['input_ids'], dim=1).to(device)
            attention_mask = torch.stack(batch['attention_mask'], dim=1).to(device)
            outputs        = model(input_ids=input_ids, attention_mask=attention_mask)
            probs          = torch.sigmoid(outputs.logits).cpu().numpy()
            all_probs.append(probs)
    return np.vstack(all_probs)

def run_config(config_name, model_name, learning_rate, batch_size,
               gradient_accumulation, num_epochs, threshold=0.3, seed=42):

    print(f"\n{'='*60}")
    print(f"CONFIG: {config_name}")
    print(f"{'='*60}")
    print(f"  Model      : {model_name}")
    print(f"  LR         : {learning_rate}")
    print(f"  Batch      : {batch_size} x {gradient_accumulation} = {batch_size*gradient_accumulation}")
    print(f"  Epochs     : {num_epochs}")
    print(f"  Max length : {MAX_LENGTH}")
    print(f"  Threshold  : {threshold}")

    device, use_fp16, use_bf16 = get_device()

    save_path = f"{OUTPUT_DIR}/roberta_models/{config_name}/best_model"
    perf_path = f"{OUTPUT_DIR}/roberta_models/{config_name}/performance"
    os.makedirs(save_path, exist_ok=True)
    os.makedirs(perf_path, exist_ok=True)

    model = RobertaForSequenceClassification.from_pretrained(
        model_name,
        num_labels=NUM_LABELS,
        problem_type="multi_label_classification",
    )
    model.to(device)

    args = TrainingArguments(
        output_dir=f"{OUTPUT_DIR}/roberta_models/{config_name}",
        num_train_epochs=num_epochs,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=gradient_accumulation,
        learning_rate=learning_rate,
        weight_decay=0.01,
        warmup_ratio=0.1,
        optim="adamw_torch",
        lr_scheduler_type="linear",
        max_grad_norm=1.0,
        eval_strategy="no",
        save_strategy="no",
        logging_steps=50,
        logging_first_step=True,
        report_to="none",
        fp16=use_fp16,
        bf16=use_bf16,
        seed=seed,
        data_seed=seed,
        dataloader_num_workers=2,
        dataloader_pin_memory=True,
        remove_unused_columns=False,
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_dataset,
        callbacks=[],
    )

    print(f"\n{'='*60}")
    print(f"TRAINING")
    print(f"{'='*60}")

    train_result = trainer.train()
    print(f"\n  Runtime    : {train_result.metrics['train_runtime']:.0f}s "
          f"({train_result.metrics['train_runtime']/3600:.1f}hrs)")
    print(f"  Final loss : {train_result.metrics['train_loss']:.4f}")

    trainer.save_model(save_path)
    tokenizer.save_pretrained(save_path)
    print(f"  Model saved: {save_path}")

    print("\nRunning holdout predictions...")
    holdout_probs = predict(holdout_dataset, model, device)
    holdout_preds = (holdout_probs >= threshold).astype(int)

    metrics = evaluate_multilabel(holdout_labels, holdout_preds, holdout_probs, CLASSES)
    print_report(metrics, CLASSES, config_name)

    hparams = {
        'learning_rate':         learning_rate,
        'batch_size':            batch_size,
        'gradient_accumulation': gradient_accumulation,
        'num_epochs':            num_epochs,
        'max_length':            MAX_LENGTH,
        'threshold':             threshold,
    }
    save_results(metrics, trainer, config_name, model_name,
                 holdout_probs, holdout_preds, perf_path, hparams)

    del model
    import gc
    gc.collect()
    torch.cuda.empty_cache()
    print(f"  GPU cleared for next config")

    return metrics['macro']['f1_macro']

print("✓ run_config() ready")

✓ run_config() ready

In [ ]:
# ── CELL 6: EXECUTE all 4 configs ────────────────────────────────────────────
import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

results = {}

results["config1_baseline"] = run_config(
    config_name          = "config1_baseline",
    model_name           = "roberta-large",
    learning_rate        = 2e-5,
    batch_size           = 8,
    gradient_accumulation= 8,
    num_epochs           = 4,
)

results["config2_higher_lr"] = run_config(
    config_name          = "config2_higher_lr",
    model_name           = "roberta-large",
    learning_rate        = 5e-5,
    batch_size           = 8,
    gradient_accumulation= 8,
    num_epochs           = 4,
)

results["config3_roberta_base"] = run_config(
    config_name          = "config3_roberta_base",
    model_name           = "roberta-base",
    learning_rate        = 2e-5,
    batch_size           = 32,
    gradient_accumulation= 2,
    num_epochs           = 4,
)

MAX_LENGTH = 256
print(f"\nRetokenizing at MAX_LENGTH={MAX_LENGTH}...")
train_dataset   = tokenize(df_train['review_text'].values,   train_labels)
val_dataset     = tokenize(df_val['review_text'].values,     val_labels)
test_dataset    = tokenize(df_test['review_text'].values,    test_labels)
holdout_dataset = tokenize(df_holdout['review_text'].values, holdout_labels)
print("✓ Retokenized")

results["config4_long_context"] = run_config(
    config_name          = "config4_long_context",
    model_name           = "roberta-large",
    learning_rate        = 2e-5,
    batch_size           = 4,
    gradient_accumulation= 16,
    num_epochs           = 4,
)

print(f"\n{'='*60}")
print("STEP 9 COMPLETE — CONFIG COMPARISON")
print(f"{'='*60}")
print(f"{'Config':<30} {'Macro F1':>10}")
print("-"*42)
for config, f1 in sorted(results.items(), key=lambda x: x[1], reverse=True):
    print(f"{config:<30} {f1:>10.4f}")
best = max(results, key=results.get)
print(f"\n✓ Best config: {best} (F1 = {results[best]:.4f})")

============================================================
CONFIG: config1_baseline
============================================================
  Model      : roberta-large
  LR         : 2e-05
  Batch      : 8 x 8 = 64
  Epochs     : 4
  Max length : 128
  Threshold  : 0.3
Device: CUDA (Tesla T4)
  VRAM: 15.6 GB

RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.out_proj.bias        | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

============================================================
TRAINING
============================================================

  Runtime    : 1380s (0.4hrs)
  Final loss : 1.5386

  Model saved: data/roberta_models/config1_baseline/best_model

Running holdout predictions...

======================================================================
HOLDOUT EVALUATION — config1_baseline
======================================================================

Class                 F1     AUC     MCC    Prec     Rec  Support
--------------------------------------------------------------
Joy               0.7388  0.9070  0.5658  0.5998  0.9616      547
Love              0.7549  0.9417  0.6839  0.8045  0.7110      353
Surprise          0.4341  0.8163  0.4319  0.8318  0.2937      303
Pride             0.0000  0.8091  0.0000  0.0000  0.0000       31
Gratitude         0.3457  0.8884  0.3345  0.5283  0.2569      109
Contentment       0.9483  0.9822  0.8486  0.9732  0.9246      982
Relief            0.5817  0.8963  0.5295  0.5122  0.6731      156
Hope              0.4423  0.9150  0.4474  0.3172  0.7302       63
Interest          0.5356  0.8547  0.4593  0.5396  0.5317      205
Anger             0.6700  0.9708  0.6461  0.6355  0.7083       96
Frustration       0.7328  0.9054  0.6262  0.7079  0.7594      399
Disappointment    0.8653  0.9599  0.7853  0.9042  0.8295      569
Sadness           0.0000  0.8010  0.0000  0.0000  0.0000      112
Fear              0.0806  0.8964  0.1772  0.8333  0.0424      118
Guilt             0.0000  0.6275  0.0000  0.0000  0.0000       82
Disgust           0.6897  0.9563  0.6698  0.7609  0.6306      111
Trust             0.8911  0.9449  0.7591  0.8666  0.9171      772
Commitment        0.8591  0.9481  0.7436  0.9168  0.8082      709
Recommendation    0.8642  0.9349  0.6835  0.9413  0.7987      924
Sentiment         0.9459  0.9810  0.8591  0.9459  0.9459      888
--------------------------------------------------------------
Macro Avg         0.5690  0.8968  0.5125  0.6310  0.5762

  Macro F1    : 0.5690  ← Primary
  Macro AUC   : 0.8968
  Macro MCC   : 0.5125
  Micro F1    : 0.7981
  Exact Match : 0.1520
  Hamming Loss: 0.1025
✓ Saved to data/roberta_models/config1_baseline/performance
  GPU cleared for next config

============================================================
CONFIG: config2_higher_lr
============================================================
  Model      : roberta-large
  LR         : 5e-05
  Batch      : 8 x 8 = 64
  Epochs     : 4
  Max length : 128
  Threshold  : 0.3
Device: CUDA (Tesla T4)
  VRAM: 15.6 GB

RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.out_proj.bias        | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

============================================================
TRAINING
============================================================

  Runtime    : 1376s (0.4hrs)
  Final loss : 1.4015

  Model saved: data/roberta_models/config2_higher_lr/best_model

Running holdout predictions...

======================================================================
HOLDOUT EVALUATION — config2_higher_lr
======================================================================

Class                 F1     AUC     MCC    Prec     Rec  Support
--------------------------------------------------------------
Joy               0.7512  0.9126  0.5884  0.6157  0.9634      547
Love              0.7570  0.9337  0.6832  0.7883  0.7280      353
Surprise          0.4498  0.8123  0.4388  0.8174  0.3102      303
Pride             0.0000  0.8253  0.0000  0.0000  0.0000       31
Gratitude         0.4494  0.8834  0.4275  0.5797  0.3670      109
Contentment       0.9460  0.9808  0.8439  0.9751  0.9185      982
Relief            0.5684  0.9058  0.5163  0.4821  0.6923      156
Hope              0.4312  0.9180  0.4406  0.3032  0.7460       63
Interest          0.5374  0.8573  0.4574  0.5157  0.5610      205
Anger             0.6432  0.9668  0.6172  0.6214  0.6667       96
Frustration       0.7417  0.9094  0.6400  0.7249  0.7594      399
Disappointment    0.8648  0.9596  0.7854  0.9073  0.8260      569
Sadness           0.0684  0.8650  0.1592  0.8000  0.0357      112
Fear              0.5562  0.9141  0.5866  0.9216  0.3983      118
Guilt             0.0000  0.6931  0.0000  0.0000  0.0000       82
Disgust           0.6916  0.9655  0.6674  0.7184  0.6667      111
Trust             0.8908  0.9440  0.7579  0.8637  0.9197      772
Commitment        0.8486  0.9469  0.7331  0.9265  0.7828      709
Recommendation    0.8593  0.9311  0.6763  0.9419  0.7900      924
Sentiment         0.9445  0.9803  0.8568  0.9499  0.9392      888
--------------------------------------------------------------
Macro Avg         0.6000  0.9053  0.5438  0.6727  0.6036

  Macro F1    : 0.6000  ← Primary
  Macro AUC   : 0.9053
  Macro MCC   : 0.5438
  Micro F1    : 0.8005
  Exact Match : 0.1520
  Hamming Loss: 0.1017
✓ Saved to data/roberta_models/config2_higher_lr/performance
  GPU cleared for next config

============================================================
CONFIG: config3_roberta_base
============================================================
  Model      : roberta-base
  LR         : 2e-05
  Batch      : 32 x 2 = 64
  Epochs     : 4
  Max length : 128
  Threshold  : 0.3
Device: CUDA (Tesla T4)
  VRAM: 15.6 GB

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.dense.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

============================================================
TRAINING
============================================================

  Runtime    : 376s (0.1hrs)
  Final loss : 0.5124

  Model saved: data/roberta_models/config3_roberta_base/best_model

Running holdout predictions...

======================================================================
HOLDOUT EVALUATION — config3_roberta_base
======================================================================

Class                 F1     AUC     MCC    Prec     Rec  Support
--------------------------------------------------------------
Joy               0.7288  0.8975  0.5503  0.5827  0.9726      547
Love              0.7710  0.9354  0.6971  0.7743  0.7677      353
Surprise          0.1212  0.6800  0.1799  0.7407  0.0660      303
Pride             0.0000  0.7754  0.0000  0.0000  0.0000       31
Gratitude         0.1270  0.8041  0.1632  0.4706  0.0734      109
Contentment       0.9424  0.9776  0.8232  0.9512  0.9338      982
Relief            0.4527  0.8358  0.3821  0.3699  0.5833      156
Hope              0.2837  0.8164  0.2488  0.2564  0.3175       63
Interest          0.4658  0.8426  0.3815  0.4842  0.4488      205
Anger             0.6465  0.9607  0.6207  0.6275  0.6667       96
Frustration       0.7057  0.8944  0.5852  0.6630  0.7544      399
Disappointment    0.8394  0.9412  0.7398  0.8627  0.8172      569
Sadness           0.0000  0.7314  0.0000  0.0000  0.0000      112
Fear              0.0000  0.7390  0.0000  0.0000  0.0000      118
Guilt             0.0000  0.5919  0.0000  0.0000  0.0000       82
Disgust           0.5385  0.9198  0.5235  0.6901  0.4414      111
Trust             0.8817  0.9365  0.7353  0.8446  0.9223      772
Commitment        0.8590  0.9423  0.7267  0.8721  0.8463      709
Recommendation    0.8756  0.9323  0.6982  0.9360  0.8225      924
Sentiment         0.9333  0.9746  0.8250  0.9296  0.9369      888
--------------------------------------------------------------
Macro Avg         0.5086  0.8565  0.4440  0.5528  0.5185

  Macro F1    : 0.5086  ← Primary
  Macro AUC   : 0.8565
  Macro MCC   : 0.4440
  Micro F1    : 0.7792
  Exact Match : 0.1332
  Hamming Loss: 0.1128
✓ Saved to data/roberta_models/config3_roberta_base/performance
  GPU cleared for next config

Retokenizing at MAX_LENGTH=256...
✓ Retokenized

============================================================
CONFIG: config4_long_context
============================================================
  Model      : roberta-large
  LR         : 2e-05
  Batch      : 4 x 16 = 64
  Epochs     : 4
  Max length : 256
  Threshold  : 0.3
Device: CUDA (Tesla T4)
  VRAM: 15.6 GB

RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.out_proj.bias        | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

============================================================
TRAINING
============================================================

  Runtime    : 2692s (0.7hrs)
  Final loss : 2.8922

  Model saved: data/roberta_models/config4_long_context/best_model

Running holdout predictions...

======================================================================
HOLDOUT EVALUATION — config4_long_context
======================================================================

Class                 F1     AUC     MCC    Prec     Rec  Support
--------------------------------------------------------------
Joy               0.7493  0.9142  0.5884  0.6073  0.9781      547
Love              0.7552  0.9379  0.6810  0.7877  0.7252      353
Surprise          0.4133  0.8267  0.4406  0.9101  0.2673      303
Pride             0.0000  0.8229  0.0000  0.0000  0.0000       31
Gratitude         0.4535  0.8748  0.4394  0.6190  0.3578      109
Contentment       0.9475  0.9869  0.8488  0.9773  0.9196      982
Relief            0.5942  0.9083  0.5459  0.5068  0.7179      156
Hope              0.4737  0.9375  0.4987  0.3273  0.8571       63
Interest          0.5450  0.8621  0.4719  0.5590  0.5317      205
Anger             0.6919  0.9739  0.6710  0.6348  0.7604       96
Frustration       0.7294  0.9098  0.6202  0.6955  0.7669      399
Disappointment    0.8796  0.9632  0.8074  0.9146  0.8471      569
Sadness           0.0000  0.7945  0.0000  0.0000  0.0000      112
Fear              0.4286  0.9115  0.4873  0.9167  0.2797      118
Guilt             0.0000  0.6264  0.0000  0.0000  0.0000       82
Disgust           0.7091  0.9631  0.6851  0.7156  0.7027      111
Trust             0.8971  0.9486  0.7720  0.8698  0.9262      772
Commitment        0.8642  0.9591  0.7535  0.9231  0.8124      709
Recommendation    0.8659  0.9398  0.6919  0.9485  0.7965      924
Sentiment         0.9557  0.9874  0.8863  0.9634  0.9482      888
--------------------------------------------------------------
Macro Avg         0.5977  0.9024  0.5445  0.6438  0.6097

  Macro F1    : 0.5977  ← Primary
  Macro AUC   : 0.9024
  Macro MCC   : 0.5445
  Micro F1    : 0.8060
  Exact Match : 0.1464
  Hamming Loss: 0.0991
✓ Saved to data/roberta_models/config4_long_context/performance
  GPU cleared for next config

============================================================
STEP 9 COMPLETE — CONFIG COMPARISON
============================================================
Config                           Macro F1
------------------------------------------
config2_higher_lr                  0.6000
config4_long_context               0.5977
config1_baseline                   0.5690
config3_roberta_base               0.5086

✓ Best config: config2_higher_lr (F1 = 0.6000)

In [ ]:
# ── Find and recover config 1 ─────────────────────────────────────────────────
import glob
from torch.utils.data import DataLoader

config_name = "config1_baseline"
base_path   = f"{OUTPUT_DIR}/roberta_models/{config_name}"
perf_path   = f"{base_path}/performance"
os.makedirs(perf_path, exist_ok=True)

# Find best checkpoint
checkpoints = sorted(glob.glob(f"{base_path}/checkpoint-*"))
print(f"Found checkpoints: {checkpoints}")

if not checkpoints:
    print("No checkpoints found — need to rerun config 1")
else:
    # Load from last checkpoint (all 4 epochs ran so last = best)
    load_path = checkpoints[-1]
    print(f"Loading from: {load_path}")

    device, use_fp16, use_bf16 = get_device()

    model     = RobertaForSequenceClassification.from_pretrained(load_path)
    tokenizer = RobertaTokenizer.from_pretrained(load_path)
    model.to(device)
    model.eval()

    def predict(dataset, model, device, batch_size=64):
        from torch.utils.data import DataLoader
        loader    = DataLoader(dataset, batch_size=batch_size)
        all_probs = []
        model.eval()
        with torch.no_grad():
            for batch in loader:
                input_ids      = torch.stack(batch['input_ids'], dim=1).to(device)
                attention_mask = torch.stack(batch['attention_mask'], dim=1).to(device)
                outputs        = model(input_ids=input_ids, attention_mask=attention_mask)
                probs          = torch.sigmoid(outputs.logits).cpu().numpy()
                all_probs.append(probs)
        return np.vstack(all_probs)

    # Re-run from here
    print("Running holdout predictions...")
    holdout_probs = predict(holdout_dataset, model, device)
    holdout_preds = (holdout_probs >= 0.5).astype(int)

    metrics = evaluate_multilabel(holdout_labels, holdout_preds, holdout_probs, CLASSES)
    print_report(metrics, CLASSES, "config1_baseline")

    hparams = {
        'learning_rate': 2e-5, 'batch_size': 32,
        'gradient_accumulation': 2, 'num_epochs': 4,
        'max_length': 128, 'threshold': 0.5,
    }
    save_results(metrics, None, "config1_baseline", "roberta-large",
                holdout_probs, holdout_preds,
                f"{OUTPUT_DIR}/roberta_models/config1_baseline/performance", hparams)

    results["config1_baseline"] = metrics['macro']['f1_macro']
    print(f"\n✓ Config 1 recovered: Macro F1 = {metrics['macro']['f1_macro']:.4f}")

Found checkpoints: ['data/roberta_models/config1_baseline/checkpoint-690', 'data/roberta_models/config1_baseline/checkpoint-920']
Loading from: data/roberta_models/config1_baseline/checkpoint-920
Device: CUDA (Tesla T4)
  VRAM: 15.6 GB

Running holdout predictions...

======================================================================
HOLDOUT EVALUATION — config1_baseline
======================================================================

Class                 F1     AUC     MCC    Prec     Rec  Support
--------------------------------------------------------------
Joy               0.7597  0.9094  0.6000  0.6351  0.9452      547
Love              0.7127  0.9403  0.6445  0.8222  0.6289      353
Surprise          0.3467  0.8022  0.3897  0.9028  0.2145      303
Pride             0.0000  0.7905  0.0000  0.0000  0.0000       31
Gratitude         0.2482  0.8884  0.2830  0.6071  0.1560      109
Contentment       0.9225  0.9814  0.7989  0.9861  0.8666      982
Relief            0.5270  0.9042  0.4739  0.5571  0.5000      156
Hope              0.4533  0.9112  0.4303  0.3908  0.5397       63
Interest          0.4532  0.8624  0.4014  0.5952  0.3659      205
Anger             0.6667  0.9688  0.6494  0.7436  0.6042       96
Frustration       0.7161  0.8998  0.6141  0.7453  0.6892      399
Disappointment    0.8451  0.9551  0.7652  0.9266  0.7768      569
Sadness           0.0000  0.8062  0.0000  0.0000  0.0000      112
Fear              0.0000  0.8667  0.0000  0.0000  0.0000      118
Guilt             0.0000  0.7002  0.0000  0.0000  0.0000       82
Disgust           0.6180  0.9516  0.6160  0.8209  0.4955      111
Trust             0.8879  0.9448  0.7622  0.8991  0.8769      772
Commitment        0.8096  0.9519  0.6875  0.9353  0.7137      709
Recommendation    0.8291  0.9381  0.6400  0.9510  0.7348      924
Sentiment         0.9323  0.9811  0.8332  0.9595  0.9065      888
--------------------------------------------------------------
Macro Avg         0.5364  0.8977  0.4795  0.6239  0.5007

  Macro F1    : 0.5364  ← Primary
  Macro AUC   : 0.8977
  Macro MCC   : 0.4795
  Micro F1    : 0.7781
  Exact Match : 0.1388
  Hamming Loss: 0.1060
✓ Saved to data/roberta_models/config1_baseline/performance

✓ Config 1 recovered: Macro F1 = 0.5364

In [ ]:
# ── Threshold tuning on config 1 results ─────────────────────────────────────
for thresh in [0.3, 0.35, 0.4, 0.45, 0.5]:
    preds   = (holdout_probs >= thresh).astype(int)
    metrics_t = evaluate_multilabel(holdout_labels, preds, holdout_probs, CLASSES)
    print(f"Threshold {thresh}: Macro F1 = {metrics_t['macro']['f1_macro']:.4f} | "
          f"Micro F1 = {metrics_t['micro']['f1_micro']:.4f}")

Threshold 0.3: Macro F1 = 0.5590 | Micro F1 = 0.7938
Threshold 0.35: Macro F1 = 0.5542 | Micro F1 = 0.7904
Threshold 0.4: Macro F1 = 0.5492 | Micro F1 = 0.7871
Threshold 0.45: Macro F1 = 0.5408 | Micro F1 = 0.7817
Threshold 0.5: Macro F1 = 0.5364 | Micro F1 = 0.7781